name: probai_causality

dependencies:
  - r-biocmanager
  - r-pcalg
  - r-rbgl
  - r-graph
  - r-rgraphviz
  - r-gpm
  - r-igraph
  - r-dagitty
  - r-causaleffect
  - r-PAGId
  - r-DOT
  - r-jsonlite
  - r-rsvg
  - r-matrixcalc
  - r-devtools