name: r_environment
dependencies:
  - r-base
  - r-essentials
  - r-devtools
  - r-biocmanager
  - r-igraph
  - r-pcalg
  - r-dagitty
  # - r-causaleffect
  - r-matrixcalc
  - r-jsonlite
  - r-rsvg
  - r-dot

channels:
  - defaults
  - conda-forge
  - bioconda

post_build:
  - |
    Rscript -e "if (!requireNamespace('BiocManager', quietly = TRUE)) install.packages('BiocManager')"
    Rscript -e "BiocManager::install(c('RBGL', 'graph', 'Rgraphviz', 'gpm'))"
    Rscript -e "install.packages('pcalg')"
    Rscript -e "install.packages('causaleffect')"
    Rscript -e "devtools::install_github('adele/PAGId', dependencies=TRUE)"
